# Generated by Django 6.0.2 on 2026-06-17 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('church', '0006_remove_membre_communaute_culte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('financement', 'Demande de financement'), ('remboursement', 'Demande de remboursement')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes_traitement', models.TextField(blank=True)),
                ('photo_recu', models.TextField(blank=True)),
                ('communaute_culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_finance', to='church.communauteculte')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.departement')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.responsable')),
            ],
            options={
                'verbose_name': 'Demande de finance',
                'verbose_name_plural': 'Demandes de finance',
                'ordering': ['-date_demande'],
            },
        ),
    ]
