# Generated by Django 6.0.2 on 2026-06-17 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0006_remove_membre_communaute_culte_and_more'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandefinance',
            name='photo_recu',
        ),
        migrations.AddField(
            model_name='demandefinance',
            name='pieces_jointes',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.CreateModel(
            name='TransactionFinance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('cotisation', 'Cotisation'), ('offrande', 'Offrande'), ('dime', 'Dîme'), ('don', 'Don'), ('entree', 'Autre entrée'), ('sortie', "Sortie d'argent"), ('depense', 'Dépense')], max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('culte_date', models.DateField(blank=True, null=True)),
                ('communaute_culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='church.communauteculte')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='church.responsable')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date'],
            },
        ),
    ]
