# Generated by Django 6.0.2 on 2026-06-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommunauteCulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Communauté de culte',
                'verbose_name_plural': 'Communautés de culte',
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('communaute_culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departements', to='church.communauteculte')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
            },
        ),
        migrations.CreateModel(
            name='Membre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sexe', models.CharField(blank=True, choices=[('feminin', 'Féminin'), ('masculin', 'Masculin'), ('autre', 'Autre')], max_length=20)),
                ('date_anniversaire', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('date_integration', models.DateField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('en_pause', 'En pause')], default='actif', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('communaute_culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='church.communauteculte')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='church.departement')),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
            },
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sexe', models.CharField(blank=True, choices=[('feminin', 'Féminin'), ('masculin', 'Masculin'), ('autre', 'Autre')], max_length=20)),
                ('date_premiere_visite', models.DateField(auto_now_add=True)),
                ('nombre_visites', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('communaute_culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visiteurs', to='church.communauteculte')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
            },
        ),
    ]
