# Generated by Django 6.0.2 on 2026-06-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membre',
            name='date_anniversaire',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
