# Generated by Django 6.0.2 on 2026-06-15 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_alter_membre_date_anniversaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('present', models.BooleanField(default=False)),
                ('communaute_culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='church.communauteculte')),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='church.membre')),
            ],
            options={
                'verbose_name': 'Présence',
                'verbose_name_plural': 'Présences',
                'unique_together': {('membre', 'date', 'communaute_culte')},
            },
        ),
    ]
