# Generated by Django 6.0.2 on 2026-06-16 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0004_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='visiteur',
            name='statut',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('contacte', 'Contacté'), ('en_suivi', 'En suivi'), ('integre', 'Intégré'), ('converti_membre', 'Converti en membre')], default='nouveau', max_length=30),
        ),
    ]
