# Generated by Django 6.0.2 on 2026-06-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0005_visiteur_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='communaute_culte',
        ),
        migrations.AddField(
            model_name='membre',
            name='communautes_culte',
            field=models.ManyToManyField(blank=True, related_name='membres', to='church.communauteculte'),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='role',
            field=models.CharField(choices=[('pasteur', 'Pasteur'), ('administrateur', 'Administrateur'), ('tresoriere', 'Trésorière'), ('secretaire', 'Secrétaire'), ('responsable_accueil', 'Responsable Accueil'), ('responsable', 'Responsable de département')], max_length=50),
        ),
    ]
