# Generated by Django 6.0.2 on 2026-06-17 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0007_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('culte', 'Culte'), ('reunion', 'Réunion'), ('formation', 'Formation'), ('evangelisation', 'Évangélisation'), ('social', 'Activité sociale'), ('anniversaire', 'Anniversaire'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('date_debut', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('tous_les_cultes', models.BooleanField(default=False)),
                ('communaute_culte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='church.communauteculte')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_debut'],
            },
        ),
    ]
