# Generated by Django 6.0.6 on 2026-06-22 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0009_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAnnuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('communaute_culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='church.communauteculte')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget annuel',
                'verbose_name_plural': 'Budgets annuels',
                'ordering': ['-annee'],
                'unique_together': {('communaute_culte', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='LigneBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('departement', 'Département'), ('operations', 'Opérations'), ('evenements', 'Événements'), ('missions', 'Missions'), ('entretien', 'Entretien'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('montant_prevu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_realise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='church.budgetannuel')),
                ('departement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_budget', to='church.departement')),
            ],
            options={
                'verbose_name': 'Ligne de budget',
                'verbose_name_plural': 'Lignes de budget',
                'ordering': ['categorie', 'description'],
            },
        ),
        migrations.CreateModel(
            name='SuiviPastoral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('sante', 'Santé'), ('famille', 'Famille'), ('spirituel', 'Spirituel'), ('financier', 'Financier'), ('integration', 'Intégration'), ('conflit', 'Conflit'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('en_cours', 'En cours'), ('resolu', 'Résolu'), ('archive', 'Archivé')], default='ouvert', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('confidentiel', models.BooleanField(default=True)),
                ('date_suivi_prochain', models.DateField(blank=True, null=True)),
                ('auteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis_crees', to=settings.AUTH_USER_MODEL)),
                ('membre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis_pastoraux', to='church.membre')),
            ],
            options={
                'verbose_name': 'Suivi pastoral',
                'verbose_name_plural': 'Suivis pastoraux',
                'ordering': ['-date_modification'],
            },
        ),
    ]
