# Generated by Django 6.0.6 on 2026-06-22 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0010_budgetannuel_lignebudget_suivipastoral'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tous_les_cultes', models.BooleanField(default=False)),
                ('contenu', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('fichier', 'Fichier'), ('sondage', 'Sondage')], default='texte', max_length=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='chat_groupe/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe', to=settings.AUTH_USER_MODEL)),
                ('communaute_culte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_groupe', to='church.communauteculte')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('date_enregistrement', models.DateTimeField(auto_now=True)),
                ('actif', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='push_token', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Push Token',
            },
        ),
        migrations.CreateModel(
            name='SondageGroupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sondage', to='church.messagegroupe')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='church.sondagegroupe')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='VoteSondage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='church.optionsondage')),
                ('votant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_sondage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('votant', 'option'), name='unique_vote_par_option')],
            },
        ),
    ]
