# Generated by Django 6.0.6 on 2026-06-23 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0011_messagegroupe_pushtoken_sondagegroupe_optionsondage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('principal', 'Groupe principal'), ('restreint', 'Groupe restreint'), ('prive', 'Conversation privée')], default='restreint', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('actif', models.BooleanField(default=True)),
                ('communaute_culte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canaux', to='church.communauteculte')),
                ('createur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canaux_crees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MessageCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('texte', 'Texte'), ('image', 'Image'), ('fichier', 'Fichier'), ('sondage', 'Sondage')], default='texte', max_length=10)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='chat/')),
                ('nom_fichier', models.CharField(blank=True, max_length=255)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('modifie', models.BooleanField(default=False)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_canal', to=settings.AUTH_USER_MODEL)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='church.canal')),
            ],
            options={
                'ordering': ['date_envoi'],
            },
        ),
        migrations.CreateModel(
            name='SondageCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('actif', models.BooleanField(default=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sondage', to='church.messagecanal')),
            ],
        ),
        migrations.CreateModel(
            name='OptionSondageCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200)),
                ('ordre', models.IntegerField(default=0)),
                ('sondage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='church.sondagecanal')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='MembreCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_admin', models.BooleanField(default=False)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='church.canal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canaux', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('canal', 'user')},
            },
        ),
        migrations.CreateModel(
            name='LectureMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_lecture', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to=settings.AUTH_USER_MODEL)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='church.messagecanal')),
            ],
            options={
                'unique_together': {('message', 'user')},
            },
        ),
        migrations.CreateModel(
            name='VoteSondageCanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vote', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='church.optionsondagecanal')),
                ('votant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_canal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('votant', 'option')},
            },
        ),
    ]
