# Generated by Django 6.0.6 on 2026-06-23 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0012_canal_messagecanal_sondagecanal_optionsondagecanal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membre',
            name='departement',
        ),
        migrations.AddField(
            model_name='membre',
            name='departements',
            field=models.ManyToManyField(blank=True, related_name='membres', to='church.departement'),
        ),
    ]
