# Generated by Django 6.0.6 on 2026-06-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0013_remove_membre_departement_membre_departements'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='responsables/photos/'),
        ),
    ]
