# Generated by Django 6.0.6 on 2026-06-23 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0014_responsable_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotePersonnelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, default='Sans titre', max_length=200)),
                ('contenu', models.TextField(blank=True)),
                ('couleur', models.CharField(choices=[('jaune', 'Jaune'), ('bleu', 'Bleu'), ('vert', 'Vert'), ('rose', 'Rose'), ('orange', 'Orange'), ('violet', 'Violet'), ('gris', 'Gris')], default='jaune', max_length=20)),
                ('epinglee', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_personnelles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-epinglee', '-date_modification'],
            },
        ),
        migrations.CreateModel(
            name='ProgrammeCulte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('theme', models.CharField(blank=True, max_length=200)),
                ('predicateur', models.CharField(blank=True, max_length=100)),
                ('verset_cle', models.CharField(blank=True, max_length=200)),
                ('notes_generales', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('communaute_culte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='church.communauteculte')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ElementProgramme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accueil', 'Accueil'), ('activite', 'Activité'), ('adoration', 'Adoration'), ('priere', 'Prière'), ('chant', 'Chant'), ('lecture', 'Lecture biblique'), ('predication', 'Prédication'), ('offrande', 'Offrande'), ('annonce', 'Annonces'), ('communion', 'Sainte Cène'), ('temoignage', 'Témoignage'), ('autre', 'Autre')], default='autre', max_length=30)),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('duree_minutes', models.IntegerField(default=5)),
                ('ordre', models.IntegerField(default=0)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('complete', models.BooleanField(default=False)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='church.programmeculte')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
    ]
